import { StyleSheet } from 'react-native';

import { webTextFont, webTextFontMedium } from '@/constants/web-text-font';

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
  },
  loaderWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollContent: {
    paddingHorizontal: 22,
    paddingTop: 24,
    paddingBottom: 36,
  },
  greetingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
    gap: 8,
  },
  greeting: {
    ...webTextFont,
    flex: 1,
    minWidth: 0,
    fontSize: 28,
    color: '#101828',
    letterSpacing: -0.8,
  },
  userDataBtn: {
    marginBottom: 14,
    width: '100%',
    alignSelf: 'stretch',
  },
  statsPanel: {
    marginBottom: 14,
  },
  statsBlock: {
    marginTop: 4,
    gap: 4,
  },
  statsSubheading: {
    ...webTextFontMedium,
    fontSize: 13,
    color: 'rgba(16, 24, 40, 0.5)',
    marginBottom: 2,
  },
  userDataModalBody: {
    width: '100%',
    alignSelf: 'stretch',
    gap: 4,
    marginTop: -4,
  },
  userDataModalTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'stretch',
    gap: 8,
    paddingVertical: 4,
    marginTop: -4,
  },
  userStatusDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    flexShrink: 0,
  },
  userStatusDotActive: {
    backgroundColor: '#22C55E',
  },
  userStatusDotInactive: {
    backgroundColor: '#EF4444',
  },
  userDataModalHeading: {
    ...webTextFont,
    fontSize: 16,
    color: '#101828',
    flexShrink: 0,
  },
  userDataTitleSep: {
    ...webTextFont,
    fontSize: 16,
    color: 'rgba(16, 24, 40, 0.35)',
    flexShrink: 0,
  },
  userDataModalUserName: {
    ...webTextFont,
    fontSize: 16,
    color: '#101828',
    flex: 1,
    minWidth: 0,
  },
  userDataModalCloseBtn: {
    marginTop: 4,
    width: '100%',
    alignSelf: 'stretch',
  },
  panelGap: {
    marginBottom: 14,
  },
  mapPanel: {
    marginBottom: 14,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#ECEDEF',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.9)',
  },
  mapTitle: {
    ...webTextFontMedium,
    fontSize: 13,
    color: 'rgba(16, 24, 40, 0.5)',
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 8,
  },
  mapContainer: {
    width: '100%',
    height: 220,
  },
  mapWebPlaceholder: {
    minHeight: 120,
    padding: 16,
    justifyContent: 'center',
  },
  mapWebPlaceholderText: {
    ...webTextFont,
    fontSize: 14,
    color: 'rgba(16, 24, 40, 0.55)',
    textAlign: 'center',
    lineHeight: 20,
  },
  mapHint: {
    ...webTextFontMedium,
    fontSize: 12,
    color: 'rgba(16, 24, 40, 0.45)',
    paddingHorizontal: 14,
    paddingBottom: 12,
    paddingTop: 4,
  },
  calendarPanel: {
    alignSelf: 'stretch',
    width: '100%',
    marginBottom: 14,
    backgroundColor: '#ECEDEF',
    borderColor: 'rgba(255, 255, 255, 0.9)',
    minHeight: 300,
  },
  profileName: {
    ...webTextFont,
    fontSize: 16,
    color: '#101828',
    marginBottom: 4,
  },
  profileLine: {
    ...webTextFont,
    fontSize: 15,
    color: '#101828',
    lineHeight: 22,
  },
  cardTitle: {
    ...webTextFont,
    fontSize: 17,
    color: '#101828',
    marginBottom: 4,
  },
  visitsCounterRow: {
    marginBottom: 10,
    gap: 2,
  },
  visitsCounterValue: {
    ...webTextFont,
    fontSize: 16,
    color: '#101828',
  },
  visitsCounterHint: {
    ...webTextFontMedium,
    fontSize: 12,
    color: 'rgba(16, 24, 40, 0.5)',
  },
  calendarLegend: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
    marginBottom: 10,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  legendSwatch: {
    width: 14,
    height: 14,
    borderRadius: 4,
  },
  legendSwatchOntime: {
    backgroundColor: '#8B5CF6',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#6D28D9',
  },
  legendSwatchLate: {
    backgroundColor: '#F97316',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#C2410C',
  },
  legendText: {
    ...webTextFontMedium,
    fontSize: 12,
    color: 'rgba(16, 24, 40, 0.55)',
  },
  historyHint: {
    ...webTextFont,
    fontSize: 13,
    color: 'rgba(16, 24, 40, 0.55)',
    lineHeight: 20,
    marginTop: 8,
  },
  calendarMonth: {
    ...webTextFont,
    flex: 1,
    minWidth: 0,
    fontSize: 14,
    color: 'rgba(16, 24, 40, 0.65)',
    textAlign: 'center',
  },
  calendarMonthRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 8,
  },
  monthNavBtn: {
    width: 32,
    height: 32,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    backgroundColor: 'rgba(16, 24, 40, 0.08)',
  },
  monthNavText: {
    ...webTextFont,
    color: '#101828',
    fontSize: 18,
    lineHeight: 20,
  },
  calendarTableWrap: {
    width: '100%',
    marginBottom: 4,
  },
  calendarTableHeaderRow: {
    flexDirection: 'row',
    width: '100%',
    marginBottom: 6,
    alignItems: 'center',
  },
  calendarTableTh: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 4,
  },
  weekHeadCell: {
    ...webTextFont,
    textAlign: 'center',
    fontSize: 13,
    lineHeight: 16,
    color: '#101828',
  },
  calendarTableBody: {
    width: '100%',
    gap: 6,
  },
  calendarTableRow: {
    flexDirection: 'row',
    width: '100%',
    alignItems: 'flex-start',
  },
  /** Ячейка «таблицы»: квадрат стороны = ширина колонки (задано в компоненте). */
  calendarTableCell: {
    padding: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarDaySquare: {
    width: '100%',
    height: '100%',
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  calendarDaySquareNeutral: {
    backgroundColor: '#D1D5DB',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(16, 24, 40, 0.12)',
  },
  calendarDaySquareMuted: {
    backgroundColor: 'rgba(208, 209, 211, 0.45)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(16, 24, 40, 0.06)',
  },
  calendarDaySquareOntime: {
    backgroundColor: '#8B5CF6',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#6D28D9',
  },
  calendarDaySquareLate: {
    backgroundColor: '#F97316',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#C2410C',
  },
  calendarDayText: {
    ...webTextFont,
    fontSize: 14,
    lineHeight: 18,
    textAlign: 'center',
    color: '#101828',
  },
  calendarDayTextOntime: {
    color: '#FFFFFF',
  },
  calendarDayTextLate: {
    color: '#FFFFFF',
  },
  mutedLine: {
    ...webTextFont,
    fontSize: 14,
    color: 'rgba(16, 24, 40, 0.55)',
  },
  status: {
    ...webTextFont,
    fontSize: 14,
    color: '#D14343',
    marginBottom: 8,
    textAlign: 'center',
  },
  generateBtn: {
    marginTop: 8,
    width: '100%',
    alignSelf: 'stretch',
  },
  logoutBtn: {
    minWidth: 0,
    paddingHorizontal: 16,
  },
  userMenuSheet: {
    alignItems: 'stretch',
    maxHeight: '70%',
  },
  menuRow: {
    paddingVertical: 14,
    paddingHorizontal: 4,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(16, 24, 40, 0.12)',
  },
  menuRowText: {
    ...webTextFontMedium,
    fontSize: 16,
    color: '#101828',
  },
  menuRowDanger: {
    color: '#D14343',
  },
  menuHint: {
    ...webTextFont,
    fontSize: 13,
    color: 'rgba(16, 24, 40, 0.55)',
    textAlign: 'center',
  },
  menuCloseBtn: {
    marginTop: 4,
    alignSelf: 'center',
  },
  editSheet: {
    alignItems: 'stretch',
    maxHeight: '85%',
  },
  editScroll: {
    width: '100%',
    maxHeight: 420,
  },
  editLabel: {
    ...webTextFontMedium,
    fontSize: 13,
    color: 'rgba(16, 24, 40, 0.65)',
    marginBottom: 6,
    marginTop: 10,
  },
  profileInput: {
    ...webTextFont,
    height: 48,
    borderRadius: 12,
    paddingHorizontal: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(16, 24, 40, 0.2)',
    color: '#101828',
    fontSize: 16,
    backgroundColor: 'rgba(16, 24, 40, 0.04)',
  },
  profileFormError: {
    ...webTextFont,
    fontSize: 14,
    color: '#D14343',
    marginTop: 10,
  },
  editSaveBtn: {
    marginTop: 18,
    width: '100%',
  },
  editCancelBtn: {
    marginTop: 10,
    alignSelf: 'center',
  },
  modalRoot: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
  },
  modalSheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 24,
    paddingTop: 10,
    paddingBottom: 28,
    alignItems: 'center',
    gap: 16,
  },
  modalHandle: {
    width: 40,
    height: 5,
    borderRadius: 3,
    backgroundColor: 'rgba(16, 24, 40, 0.15)',
    marginBottom: 4,
  },
  modalTitle: {
    ...webTextFont,
    fontSize: 18,
    color: '#101828',
    textAlign: 'center',
  },
  modalSubtitle: {
    ...webTextFontMedium,
    fontSize: 14,
    color: 'rgba(16, 24, 40, 0.55)',
    textAlign: 'center',
    marginTop: -8,
  },
  qrBox: {
    padding: 12,
    backgroundColor: '#fff',
    borderRadius: 16,
  },
  qrWithLogo: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  qrCode: {
    backgroundColor: '#FFFFFF',
  },
  qrLogoBackdrop: {
    position: 'absolute',
    width: 64,
    height: 64,
    top: '50%',
    left: '50%',
    marginTop: -32,
    marginLeft: -32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(16, 24, 40, 0.1)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  qrLogoOverlay: {
    width: 48,
    height: 48,
    borderRadius: 8,
  },
});
